on:
  push:
name: publish
jobs:
  generate:
    name: "Generate static HTML"
    runs-on: ubuntu-latest
    steps:
      - name: "Generate static HTML"
        id: generate
        uses: estebanlm/foliage-action
        with:
          source: "."
          target: "generated"
