on:
  push:

name: publish

jobs:
  generate: 
    name: "Generate site"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: "Generate static HTML"
        uses: estebanlm/foliage-action@v1
      - name: "Upload to server"
        uses: up9cloud/action-rsync@v1.3
        env:
          KEY: ${{ secrets.SERVER_SSH_KEY }}
          USER: ${{ secrets.REMOTE_USER }}
          HOST: ${{ secrets.REMOTE_HOST }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SOURCE: "generated"
          SSH_ARGS: '-p 22 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=VERBOSE'
          VERBOSE: true
